dist: trusty
sudo: false

language: node_js
node_js:
  - '10.19.0'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install
  
script:
  - npm test 
  - npm run codecov
  
after_script:
	- bash <(curl -s https://codecov.io/bash)